  type: rpm-ostree
  repos:
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/hl2linux-selinux/repo/fedora-%OS_VERSION%/kylegospo-hl2linux-selinux-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
  install:
    # - micro
    - starship
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-just-perfection
    - gnome-shell-extension-caffeine
    - gnome-shell-extension-blur-my-shell
    - gnome-shell-extension-user-theme
    - gnome-shell-extension-dash-to-dock
    - gnome-console
    - hl2linux-selinux
    - system76-scheduler
    - gnome-shell-extension-system76-scheduler
    - morewaita-icon-theme
    - code
    - nautilus-python
    - nautilus-dropbox
    - yaru-theme
    # - gnome-shell-theme-flat-remix
  remove:
    - firefox # default firefox removed in favor of flatpak
    - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
    - gnome-terminal
    - gnome-terminal-nautilus
    - gnome-tour
    - gnome-system-monitor
    - gnome-software-rpm-ostree
    - htop
    - nvtop